name: morphocluster
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy>=1.17.2
  - pandas
  - h5py>=2.8.0
  - scikit-learn<=0.21
  - scipy
  - pip
  - hdbscan
  - pip:
    - gunicorn
    - flask>=1.0.2
    - psycopg2-binary
    - sqlalchemy >= 1.3
    - redis >= 3.0, < 3.1
    - hiredis
    - alembic
    - Flask-SQLAlchemy
    - flask-redis
    - Flask-Migrate
    - fire
    - marshmallow>=3.0.0b20
    - match_arrays
    - Flask-RQ2
    - tqdm

