name: morphocluster
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy>=1.17.2
  - pandas
  - h5py>=3.1.0
  - scikit-learn<=0.21
  - scipy
  - pip
  - hdbscan
  - nodejs
  - Pillow
  - pytorch
  - torchvision
  # Replace by the correction version of cudatoolkit to enable GPU feature extraction,
  # e.g. "cudatoolkit=10.2"
  - cpuonly

  - pip:
    - gunicorn
    - flask>=1.0.2
    - psycopg2-binary
    - sqlalchemy >= 1.3
    - redis >= 3.0, < 3.1
    - hiredis
    - alembic
    - Flask-SQLAlchemy
    - flask-redis
    - Flask-Migrate
    - fire
    - marshmallow>=3.0.0b20
    - match_arrays
    - Flask-RQ2
    - tqdm
    - Click==7.1.2
    - chardet
